<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.550">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>practicafinal</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="0-PracticaFinal_files/libs/clipboard/clipboard.min.js"></script>
<script src="0-PracticaFinal_files/libs/quarto-html/quarto.js"></script>
<script src="0-PracticaFinal_files/libs/quarto-html/popper.min.js"></script>
<script src="0-PracticaFinal_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="0-PracticaFinal_files/libs/quarto-html/anchor.min.js"></script>
<link href="0-PracticaFinal_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="0-PracticaFinal_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="0-PracticaFinal_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="0-PracticaFinal_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="0-PracticaFinal_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Cargar los datos en un dataframe llamado: airbnb</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>airbnb<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">'data//airbnb.csv'</span>,<span class="at">sep =</span> <span class="st">','</span>, <span class="at">stringsAsFactors =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Mostrar las primeras 6 filas del dataframe</p>
<p>Renombrar las columnas de la siguiente forma:</p>
<table class="table">
<thead>
<tr class="header">
<th>Nombre original</th>
<th>Nuevo nombre</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Zipcode</td>
<td>CodigoPostal</td>
</tr>
<tr class="even">
<td>Neighbourhood.Cleansed</td>
<td>Barrio</td>
</tr>
<tr class="odd">
<td>Property.Type</td>
<td>TipoPropiedad</td>
</tr>
<tr class="even">
<td>Room.Type</td>
<td>TipoAlquiler</td>
</tr>
<tr class="odd">
<td>Accommodates</td>
<td>MaxOcupantes</td>
</tr>
<tr class="even">
<td>Bathrooms</td>
<td>NumBanyos</td>
</tr>
<tr class="odd">
<td>Bedrooms</td>
<td>NumDormitorios</td>
</tr>
<tr class="even">
<td>Beds</td>
<td>NumCamas</td>
</tr>
<tr class="odd">
<td>Bed.Type</td>
<td>TipoCama</td>
</tr>
<tr class="even">
<td>Amenities</td>
<td>Comodidades</td>
</tr>
<tr class="odd">
<td>Square.Feet</td>
<td>PiesCuadrados</td>
</tr>
<tr class="even">
<td>Price</td>
<td>Precio</td>
</tr>
<tr class="odd">
<td>Review.Scores.Rating</td>
<td>Puntuacion</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#newnames&lt;-c("CodigoPostal","Barrio","TipoPropiedad","TipoAlquiler","MaxOcupantes","NumBanyos",</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co">#"NumDormitorios","NumCamas","TipoCama","Comodidades","PiesCuadrados","Precio","Puntuacion")</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Nuevo vector de nombres para las columnas</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>newnames <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"CodigoPostal"</span>, <span class="st">"Barrio"</span>, <span class="st">"TipoPropiedad"</span>, <span class="st">"TipoAlquiler"</span>, <span class="st">"MaxOcupantes"</span>, </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>              <span class="st">"NumBanyos"</span>, <span class="st">"NumDormitorios"</span>, <span class="st">"NumCamas"</span>, <span class="st">"TipoCama"</span>, <span class="st">"Comodidades"</span>, </span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>              <span class="st">"PiesCuadrados"</span>, <span class="st">"Precio"</span>, <span class="st">"Puntuacion"</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">length</span>(newnames) <span class="sc">==</span> <span class="fu">length</span>(<span class="fu">names</span>(airbnb))) {</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">names</span>(airbnb) <span class="ot">&lt;-</span> newnames</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stop</span>(<span class="st">"El número de nombres nuevos no coincide con el número de columnas en el dataframe."</span>)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(airbnb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "CodigoPostal"   "Barrio"         "TipoPropiedad"  "TipoAlquiler"  
 [5] "MaxOcupantes"   "NumBanyos"      "NumDormitorios" "NumCamas"      
 [9] "TipoCama"       "Comodidades"    "PiesCuadrados"  "Precio"        
[13] "Puntuacion"    </code></pre>
</div>
</div>
<ol type="1">
<li>Crea una nueva columna llamada MetrosCuadrados a partir de la columna PiesCuadrados.</li>
</ol>
<p>Ayuda: 1 pie cuadrado son 0,092903 metros cuadrdados</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear columna MetrosCuadrados</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>MetrosCuadrados <span class="ot">&lt;-</span> airbnb<span class="sc">$</span>PiesCuadrados <span class="sc">*</span> <span class="fl">0.092903</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airbnb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  CodigoPostal      Barrio TipoPropiedad    TipoAlquiler MaxOcupantes NumBanyos
1        28004 Universidad     Apartment    Private room            2         2
2        28004 Universidad     Apartment Entire home/apt            6         1
3        28004 Universidad     Apartment Entire home/apt            3         1
4        28004 Universidad          Loft Entire home/apt            3         2
5        28015 Universidad     Apartment Entire home/apt            5         1
6        28004 Universidad     Apartment Entire home/apt            2         1
  NumDormitorios NumCamas TipoCama
1              1        1 Real Bed
2              3        5 Real Bed
3              2        2 Real Bed
4              1        1 Real Bed
5              1        1 Real Bed
6              0        1 Real Bed
                                                                                                                                                                                                                                                                                                                                                       Comodidades
1                                                                                                                                                                              TV,Wireless Internet,Kitchen,Pets allowed,Pets live on this property,Buzzer/wireless intercom,Heating,Suitable for events,Washer,First aid kit,Essentials,Lock on bedroom door,Iron
2                                                                                                                                                                                      TV,Internet,Wireless Internet,Air conditioning,Kitchen,Indoor fireplace,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,Essentials,Shampoo
3                                                                                                                                                                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Doorman,Heating,Family/kid friendly,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace
4                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Pets allowed,Breakfast,Elevator in building,Indoor fireplace,Buzzer/wireless intercom,Heating,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace,translation missing: en.hosting_amenity_49,translation missing: en.hosting_amenity_50
5                                                                                                                                                                                                               TV,Wireless Internet,Air conditioning,Kitchen,Smoking allowed,Pets allowed,Elevator in building,Heating,Family/kid friendly,Washer,Essentials,Iron
6 TV,Cable TV,Internet,Wireless Internet,Air conditioning,Wheelchair accessible,Kitchen,Doorman,Elevator in building,Buzzer/wireless intercom,Heating,Washer,Smoke detector,Carbon monoxide detector,First aid kit,Safety card,Fire extinguisher,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace,Self Check-In,Doorman Entry
  PiesCuadrados Precio Puntuacion MetrosCuadrados
1            NA     35         NA              NA
2            NA     92         96              NA
3            NA     55         91              NA
4            NA     60        100              NA
5           538     75         90        49.98181
6            NA     55         95              NA</code></pre>
</div>
</div>
<hr>
<ol start="2" type="1">
<li>Miremos el código postal. Es una variable con entradas erroneas. Hay valores como ’‘,’-’ y ‘28’ que deberían ser considerados como NA. Así mismo también debería ser NA todos los que no compiencen por 28, ya que estamos con códigos postales de Madrid</li>
</ol>
<p>El código postal 28002, 28004 y 28051 tienen entradas repetidas. Por ejemplo las entradas 28002 deberían ir dnetro de 28002</p>
<p>El codigo 2804 debería ser 28004, 2805 deberia ser 28005 y 2815 juncto con 2815 debería ser 28015</p>
<p>Limpia los datos de la columna Codigo Postal</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Asegurarse de que CodigoPostal sea de tipo string</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal <span class="ot">&lt;-</span> <span class="fu">as.character</span>(airbnb<span class="sc">$</span>CodigoPostal)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Reemplazar valores vacíos y '-' por NA</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal[airbnb<span class="sc">$</span>CodigoPostal <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">''</span>, <span class="st">'-'</span>)] <span class="ot">&lt;-</span> <span class="cn">NA</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airbnb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  CodigoPostal      Barrio TipoPropiedad    TipoAlquiler MaxOcupantes NumBanyos
1        28004 Universidad     Apartment    Private room            2         2
2        28004 Universidad     Apartment Entire home/apt            6         1
3        28004 Universidad     Apartment Entire home/apt            3         1
4        28004 Universidad          Loft Entire home/apt            3         2
5        28015 Universidad     Apartment Entire home/apt            5         1
6        28004 Universidad     Apartment Entire home/apt            2         1
  NumDormitorios NumCamas TipoCama
1              1        1 Real Bed
2              3        5 Real Bed
3              2        2 Real Bed
4              1        1 Real Bed
5              1        1 Real Bed
6              0        1 Real Bed
                                                                                                                                                                                                                                                                                                                                                       Comodidades
1                                                                                                                                                                              TV,Wireless Internet,Kitchen,Pets allowed,Pets live on this property,Buzzer/wireless intercom,Heating,Suitable for events,Washer,First aid kit,Essentials,Lock on bedroom door,Iron
2                                                                                                                                                                                      TV,Internet,Wireless Internet,Air conditioning,Kitchen,Indoor fireplace,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,Essentials,Shampoo
3                                                                                                                                                                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Doorman,Heating,Family/kid friendly,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace
4                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Pets allowed,Breakfast,Elevator in building,Indoor fireplace,Buzzer/wireless intercom,Heating,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace,translation missing: en.hosting_amenity_49,translation missing: en.hosting_amenity_50
5                                                                                                                                                                                                               TV,Wireless Internet,Air conditioning,Kitchen,Smoking allowed,Pets allowed,Elevator in building,Heating,Family/kid friendly,Washer,Essentials,Iron
6 TV,Cable TV,Internet,Wireless Internet,Air conditioning,Wheelchair accessible,Kitchen,Doorman,Elevator in building,Buzzer/wireless intercom,Heating,Washer,Smoke detector,Carbon monoxide detector,First aid kit,Safety card,Fire extinguisher,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace,Self Check-In,Doorman Entry
  PiesCuadrados Precio Puntuacion MetrosCuadrados
1            NA     35         NA              NA
2            NA     92         96              NA
3            NA     55         91              NA
4            NA     60        100              NA
5           538     75         90        49.98181
6            NA     55         95              NA</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reemplaza valores que no empiezan por 28 por NA</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal[<span class="sc">!</span><span class="fu">grepl</span>(<span class="st">'^28'</span>, airbnb<span class="sc">$</span>CodigoPostal)] <span class="ot">&lt;-</span> <span class="cn">NA</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airbnb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  CodigoPostal      Barrio TipoPropiedad    TipoAlquiler MaxOcupantes NumBanyos
1        28004 Universidad     Apartment    Private room            2         2
2        28004 Universidad     Apartment Entire home/apt            6         1
3        28004 Universidad     Apartment Entire home/apt            3         1
4        28004 Universidad          Loft Entire home/apt            3         2
5        28015 Universidad     Apartment Entire home/apt            5         1
6        28004 Universidad     Apartment Entire home/apt            2         1
  NumDormitorios NumCamas TipoCama
1              1        1 Real Bed
2              3        5 Real Bed
3              2        2 Real Bed
4              1        1 Real Bed
5              1        1 Real Bed
6              0        1 Real Bed
                                                                                                                                                                                                                                                                                                                                                       Comodidades
1                                                                                                                                                                              TV,Wireless Internet,Kitchen,Pets allowed,Pets live on this property,Buzzer/wireless intercom,Heating,Suitable for events,Washer,First aid kit,Essentials,Lock on bedroom door,Iron
2                                                                                                                                                                                      TV,Internet,Wireless Internet,Air conditioning,Kitchen,Indoor fireplace,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,Essentials,Shampoo
3                                                                                                                                                                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Doorman,Heating,Family/kid friendly,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace
4                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Pets allowed,Breakfast,Elevator in building,Indoor fireplace,Buzzer/wireless intercom,Heating,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace,translation missing: en.hosting_amenity_49,translation missing: en.hosting_amenity_50
5                                                                                                                                                                                                               TV,Wireless Internet,Air conditioning,Kitchen,Smoking allowed,Pets allowed,Elevator in building,Heating,Family/kid friendly,Washer,Essentials,Iron
6 TV,Cable TV,Internet,Wireless Internet,Air conditioning,Wheelchair accessible,Kitchen,Doorman,Elevator in building,Buzzer/wireless intercom,Heating,Washer,Smoke detector,Carbon monoxide detector,First aid kit,Safety card,Fire extinguisher,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace,Self Check-In,Doorman Entry
  PiesCuadrados Precio Puntuacion MetrosCuadrados
1            NA     35         NA              NA
2            NA     92         96              NA
3            NA     55         91              NA
4            NA     60        100              NA
5           538     75         90        49.98181
6            NA     55         95              NA</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ver de que CodigoPostal sea de tipo string</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal <span class="ot">&lt;-</span> <span class="fu">as.character</span>(airbnb<span class="sc">$</span>CodigoPostal)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Reemplazar con NA los códigos postales que no comienzan con '28'</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="fu">substr</span>(airbnb<span class="sc">$</span>CodigoPostal, <span class="dv">1</span>, <span class="dv">2</span>) <span class="sc">!=</span> <span class="st">'28'</span>, <span class="cn">NA</span>, airbnb<span class="sc">$</span>CodigoPostal)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtener y mostrar todos los valores únicos de CodigoPostal</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>codigos_postales_unicos <span class="ot">&lt;-</span> <span class="fu">unique</span>(airbnb<span class="sc">$</span>CodigoPostal)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(codigos_postales_unicos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "28004"        "28015"        "28013"        "28005"        "28012"       
 [6] "28014"        "28045"        NA             "28007"        "28028"       
[11] "28009"        "28001"        "28006"        "28010"        "28002"       
[16] "28034"        "28050"        "28008"        "28011"        "28049"       
[21] "28038"        "28053"        "28047"        "28025"        "28019"       
[26] "28024"        "28016"        "28036"        "28046"        "28039"       
[31] "28020"        "28003"        "28029"        "28054"        "28041"       
[36] "28026"        "28058"        "28018"        "28030"        "28017"       
[41] "28027"        "28043"        "28033"        "28055"        "28021"       
[46] "28032"        "28037"        "28022"        "28042"        "28094"       
[51] "280013"       "28002\n28002" "28035"        "28040"        "28031"       
[56] "28044"        "28105"        "28023"        "2805"         "28051"       
[61] "28051\n28051" "28850"        "28048"        "28056"        "28060"       
[66] "28"           "2815"         "28052"        "2804"        </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Asegurarse de que CodigoPostal sea de tipo string</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal <span class="ot">&lt;-</span> <span class="fu">as.character</span>(airbnb<span class="sc">$</span>CodigoPostal)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Dividir los códigos postales en '\n' y seleccionar la primera parte</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="fu">strsplit</span>(airbnb<span class="sc">$</span>CodigoPostal, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>), <span class="st">`</span><span class="at">[</span><span class="st">`</span>, <span class="dv">1</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Se verifican los valores únicos después de la corrección</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>unique_codigos_postales <span class="ot">&lt;-</span> <span class="fu">unique</span>(airbnb<span class="sc">$</span>CodigoPostal)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(unique_codigos_postales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "28004"  "28015"  "28013"  "28005"  "28012"  "28014"  "28045"  NA      
 [9] "28007"  "28028"  "28009"  "28001"  "28006"  "28010"  "28002"  "28034" 
[17] "28050"  "28008"  "28011"  "28049"  "28038"  "28053"  "28047"  "28025" 
[25] "28019"  "28024"  "28016"  "28036"  "28046"  "28039"  "28020"  "28003" 
[33] "28029"  "28054"  "28041"  "28026"  "28058"  "28018"  "28030"  "28017" 
[41] "28027"  "28043"  "28033"  "28055"  "28021"  "28032"  "28037"  "28022" 
[49] "28042"  "28094"  "280013" "28035"  "28040"  "28031"  "28044"  "28105" 
[57] "28023"  "2805"   "28051"  "28850"  "28048"  "28056"  "28060"  "28"    
[65] "2815"   "28052"  "2804"  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Se corrige el código postal de '2804' a '28004'</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"^2804$"</span>, <span class="st">"28004"</span>, airbnb<span class="sc">$</span>CodigoPostal)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Se corriger el código postal de '2805' a '28005'</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"^2805$"</span>, <span class="st">"28005"</span>, airbnb<span class="sc">$</span>CodigoPostal)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="co"># se corrige el código postal de '2815' a '28015'</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"^2815$"</span>, <span class="st">"28015"</span>, airbnb<span class="sc">$</span>CodigoPostal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<ol start="3" type="1">
<li>Una vez limpios los datos ¿Cuales son los códigos postales que tenemos?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificar los valores únicos después de las correcciones</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>unique_codigos_postales <span class="ot">&lt;-</span> <span class="fu">unique</span>(airbnb<span class="sc">$</span>CodigoPostal)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(unique_codigos_postales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "28004"  "28015"  "28013"  "28005"  "28012"  "28014"  "28045"  NA      
 [9] "28007"  "28028"  "28009"  "28001"  "28006"  "28010"  "28002"  "28034" 
[17] "28050"  "28008"  "28011"  "28049"  "28038"  "28053"  "28047"  "28025" 
[25] "28019"  "28024"  "28016"  "28036"  "28046"  "28039"  "28020"  "28003" 
[33] "28029"  "28054"  "28041"  "28026"  "28058"  "28018"  "28030"  "28017" 
[41] "28027"  "28043"  "28033"  "28055"  "28021"  "28032"  "28037"  "28022" 
[49] "28042"  "28094"  "280013" "28035"  "28040"  "28031"  "28044"  "28105" 
[57] "28023"  "28051"  "28850"  "28048"  "28056"  "28060"  "28"     "28052" </code></pre>
</div>
</div>
<hr>
<ol start="4" type="1">
<li>¿Cuales son los 5 códigos postales con más entradas? ¿Y con menos? ¿Cuantas entradas tienen?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Asegúrate de que la columna CodigoPostal sea de tipo string</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal <span class="ot">&lt;-</span> <span class="fu">as.character</span>(airbnb<span class="sc">$</span>CodigoPostal)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Contar las entradas para cada código postal</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>conteo_codigos_postales <span class="ot">&lt;-</span> <span class="fu">table</span>(airbnb<span class="sc">$</span>CodigoPostal)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Ordenar los conteos de mayor a menor y seleccionar los 5 con más entradas</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>codigos_postales_mas_entradas <span class="ot">&lt;-</span> <span class="fu">sort</span>(conteo_codigos_postales, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Ordenar los conteos de menor a mayor y seleccionar los 5 con menos entradas</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Excluir los códigos postales con NA o conteos de 0</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>codigos_postales_menos_entradas <span class="ot">&lt;-</span> <span class="fu">sort</span>(conteo_codigos_postales[conteo_codigos_postales <span class="sc">&gt;</span> <span class="dv">0</span>], <span class="at">decreasing =</span> <span class="cn">FALSE</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar los resultados</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Los 5 códigos postales con más entradas son:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Los 5 códigos postales con más entradas son:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(codigos_postales_mas_entradas)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
28012 28004 28005 28013 28014 
 2060  1795  1195  1019   630 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Los 5 códigos postales con menos entradas son:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Los 5 códigos postales con menos entradas son:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(codigos_postales_menos_entradas)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    28 280013  28048  28052  28056 
     1      1      1      1      1 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Conteo de entradas para cada código postal:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Conteo de entradas para cada código postal:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conteo_codigos_postales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    28  28001 280013  28002  28003  28004  28005  28006  28007  28008  28009 
     1    231      1    171    185   1795   1195    218    206    338    216 
 28010  28011  28012  28013  28014  28015  28016  28017  28018  28019  28020 
   384    250   2060   1019    630    601     76    107     43    200    192 
 28021  28022  28023  28024  28025  28026  28027  28028  28029  28030  28031 
    58     30     23     44    123     93    122    263    110     73     27 
 28032  28033  28034  28035  28036  28037  28038  28039  28040  28041  28042 
    33     89     45     59     67     65     77    160     16     63     90 
 28043  28044  28045  28046  28047  28048  28049  28050  28051  28052  28053 
   103     19    495     32     67      1      3     58     17      1     85 
 28054  28055  28056  28058  28060  28094  28105  28850 
    12     12      1      1      1      1      1      1 </code></pre>
</div>
</div>
<hr>
<ol start="5" type="1">
<li>¿Cuales son los barrios que hay en el código postal 28012?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar el DataFrame para el código postal 28012</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>datos_28012 <span class="ot">&lt;-</span> <span class="fu">subset</span>(airbnb, CodigoPostal <span class="sc">==</span> <span class="st">'28012'</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtener los barrios únicos en el código postal 28012</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>barrios_28012 <span class="ot">&lt;-</span> <span class="fu">unique</span>(datos_28012<span class="sc">$</span>Barrio)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar los barrios</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Los barrios en el código postal 28012 son:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Los barrios en el código postal 28012 son:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(barrios_28012)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] Sol             Acacias         Palos de Moguer Embajadores    
 [5] Cortes          Palacio         Universidad     Delicias       
 [9] Arapiles        Atocha          Goya           
125 Levels: Abrantes Acacias Adelfas Aeropuerto Aguilas ... Zofío</code></pre>
</div>
</div>
<hr>
<ol start="6" type="1">
<li>¿Cuantas entradas hay en cada uno de esos barrios para el codigo postal 28012?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar el DataFrame para el código postal 28012</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>datos_28012 <span class="ot">&lt;-</span> <span class="fu">subset</span>(airbnb, CodigoPostal <span class="sc">==</span> <span class="st">'28012'</span>)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Agrupar por barrio y contar las entradas en cada uno</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>conteo_barrios_28012 <span class="ot">&lt;-</span> <span class="fu">table</span>(datos_28012<span class="sc">$</span>Barrio)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar el número de entradas por barrio para el código postal 28012</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Número de entradas por barrio para el código postal 28012:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Número de entradas por barrio para el código postal 28012:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conteo_barrios_28012)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                    Abrantes                      Acacias 
                           0                           13 
                     Adelfas                   Aeropuerto 
                           0                            0 
                     Aguilas             Alameda de Osuna 
                           0                            0 
                     Almagro                     Almenara 
                           0                            0 
                 Almendrales                       Aluche 
                           0                            0 
                      Ambroz                      Amposta 
                           0                            0 
            Apostol Santiago                     Arapiles 
                           0                            1 
                     Aravaca                        Arcos 
                           0                            0 
                   Argüelles                       Atocha 
                           0                            1 
               Bellas Vistas                   Berruguete 
                           0                            0 
                  Buenavista                     Butarque 
                           0                            0 
                  Campamento                     Canillas 
                           0                            0 
                  Canillejas                     Cármenes 
                           0                            0 
               Casa de Campo   Casco Histórico de Barajas 
                           0                            0 
 Casco Histórico de Vallecas Casco Histórico de Vicálvaro 
                           0                            0 
                  Castellana                     Castilla 
                           0                            0 
                 Castillejos                      Chopera 
                           0                            0 
               Ciudad Jardín         Ciudad Universitaria 
                           0                            0 
                      Colina                     Comillas 
                           0                            0 
                  Concepción                   Corralejos 
                           0                            0 
                      Cortes                  Costillares 
                         216                            0 
              Cuatro Caminos               Cuatro Vientos 
                           0                            0 
                    Delicias                    El Goloso 
                           1                            0 
                  El Plantío                      El Viso 
                           0                            0 
                 Embajadores                    Entrevías 
                        1449                            0 
                    Estrella                    Fontarrón 
                           0                            0 
            Fuente del Berro                Fuentelareina 
                           0                            0 
                  Gaztambide                         Goya 
                           0                            1 
                  Guindalera                       Hellín 
                           0                            0 
              Hispanoamérica                        Ibiza 
                           0                            0 
                    Imperial                    Jerónimos 
                           0                            0 
                    Justicia                       La Paz 
                           0                            0 
                     Legazpi                        Lista 
                           0                            0 
                 Los Angeles                  Los Rosales 
                           0                            0 
                      Lucero                   Marroquina 
                           0                            0 
                 Media Legua                   Mirasierra 
                           0                            0 
                    Moscardó                   Niño Jesús 
                           0                            0 
                Nueva España                     Numancia 
                           0                            0 
                      Opañel                    Orcasitas 
                           0                            0 
                     Orcasur                     Pacífico 
                           0                            0 
                     Palacio                      Palomas 
                          27                            0 
             Palomeras Bajas            Palomeras Sureste 
                           0                            0 
             Palos de Moguer                      Pavones 
                          46                            0 
                  Peñagrande                        Pilar 
                           0                            0 
               Pinar del Rey                      Piovera 
                           0                            0 
                    Portazgo                   Pradolongo 
                           0                            0 
                 Prosperidad                 Pueblo Nuevo 
                           0                            0 
               Puerta Bonita             Puerta del Angel 
                           0                            0 
                    Quintana                    Recoletos 
                           0                            0 
                       Rejas                   Rios Rosas 
                           0                            0 
                       Rosas                     Salvador 
                           0                            0 
                  San Andrés                San Cristobal 
                           0                            0 
                   San Diego                   San Fermín 
                           0                            0 
                  San Isidro            San Juan Bautista 
                           0                            0 
                 San Pascual                Santa Eugenia 
                           0                            0 
                    Simancas                          Sol 
                           0                          301 
                       Timón                    Trafalgar 
                           0                            0 
                 Universidad                Valdeacederas 
                           4                            0 
                Valdefuentes                   Valdemarín 
                           0                            0 
                  Valdezarza                 Vallehermoso 
                           0                            0 
                    Valverde                       Ventas 
                           0                            0 
                   Vinateros                 Vista Alegre 
                           0                            0 
                       Zofío 
                           0 </code></pre>
</div>
</div>
<hr>
<ol start="7" type="1">
<li>¿Cuantos barrios hay en todo el dataset airbnb? ¿Cuales son?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Asegúrate de que la columna Barrio sea de tipo string</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>Barrio <span class="ot">&lt;-</span> <span class="fu">as.character</span>(airbnb<span class="sc">$</span>Barrio)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtener los barrios únicos en todo el dataset</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>barrios_unicos <span class="ot">&lt;-</span> <span class="fu">unique</span>(airbnb<span class="sc">$</span>Barrio)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Contar cuántos barrios únicos hay</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>numero_barrios <span class="ot">&lt;-</span> <span class="fu">length</span>(barrios_unicos)</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar el número de barrios y los barrios</span></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Número de barrios únicos en el dataset:"</span>, numero_barrios))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Número de barrios únicos en el dataset: 125"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Barrios únicos en el dataset:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Barrios únicos en el dataset:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(barrios_unicos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] "Universidad"                  "Sol"                         
  [3] "Imperial"                     "Acacias"                     
  [5] "Chopera"                      "Delicias"                    
  [7] "Palos de Moguer"              "Embajadores"                 
  [9] "Cortes"                       "Atocha"                      
 [11] "Pacífico"                     "Adelfas"                     
 [13] "Estrella"                     "Ibiza"                       
 [15] "Jerónimos"                    "Niño Jesús"                  
 [17] "Palacio"                      "Justicia"                    
 [19] "Recoletos"                    "Goya"                        
 [21] "Fuente del Berro"             "Arapiles"                    
 [23] "Trafalgar"                    "Almagro"                     
 [25] "Guindalera"                   "Lista"                       
 [27] "Castellana"                   "El Viso"                     
 [29] "Prosperidad"                  "Valverde"                    
 [31] "Casa de Campo"                "El Goloso"                   
 [33] "Numancia"                     "Cármenes"                    
 [35] "Puerta del Angel"             "Lucero"                      
 [37] "Aluche"                       "San Isidro"                  
 [39] "Campamento"                   "Comillas"                    
 [41] "Opañel"                       "Vista Alegre"                
 [43] "Ciudad Jardín"                "Hispanoamérica"              
 [45] "Nueva España"                 "Castilla"                    
 [47] "Bellas Vistas"                "Cuatro Caminos"              
 [49] "Castillejos"                  "Vallehermoso"                
 [51] "Almenara"                     "Valdeacederas"               
 [53] "Berruguete"                   "Gaztambide"                  
 [55] "Rios Rosas"                   "Peñagrande"                  
 [57] "Argüelles"                    "Puerta Bonita"               
 [59] "Buenavista"                   "Abrantes"                    
 [61] "Orcasur"                      "San Fermín"                  
 [63] "Almendrales"                  "Pradolongo"                  
 [65] "Portazgo"                     "Entrevías"                   
 [67] "San Diego"                    "Palomeras Bajas"             
 [69] "Fontarrón"                    "Vinateros"                   
 [71] "Ventas"                       "Pueblo Nuevo"                
 [73] "Quintana"                     "Concepción"                  
 [75] "San Juan Bautista"            "Costillares"                 
 [77] "Piovera"                      "Canillas"                    
 [79] "Pinar del Rey"                "Apostol Santiago"            
 [81] "San Andrés"                   "Valdefuentes"                
 [83] "Butarque"                     "Los Angeles"                 
 [85] "Casco Histórico de Vicálvaro" "Simancas"                    
 [87] "Rejas"                        "Salvador"                    
 [89] "Casco Histórico de Barajas"   "Pilar"                       
 [91] "La Paz"                       "Mirasierra"                  
 [93] "Ciudad Universitaria"         "Moscardó"                    
 [95] "Palomeras Sureste"            "Marroquina"                  
 [97] "Media Legua"                  "Los Rosales"                 
 [99] "Casco Histórico de Vallecas"  "Timón"                       
[101] "Corralejos"                   "Cuatro Vientos"              
[103] "Colina"                       "San Cristobal"               
[105] "Alameda de Osuna"             "Aeropuerto"                  
[107] "Palomas"                      "Zofío"                       
[109] "Aguilas"                      "Legazpi"                     
[111] "Fuentelareina"                "Aravaca"                     
[113] "Ambroz"                       "Canillejas"                  
[115] "Valdezarza"                   "Amposta"                     
[117] "San Pascual"                  "Santa Eugenia"               
[119] "Arcos"                        "Rosas"                       
[121] "Valdemarín"                   "El Plantío"                  
[123] "Hellín"                       "Pavones"                     
[125] "Orcasitas"                   </code></pre>
</div>
</div>
<hr>
<ol start="8" type="1">
<li>¿Cuales son los 5 barrios que tienen mayor número entradas?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Asegúrate de que la columna Barrio sea de tipo string</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>Barrio <span class="ot">&lt;-</span> <span class="fu">as.character</span>(airbnb<span class="sc">$</span>Barrio)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Contar las entradas en cada barrio y ordenar</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>conteo_barrios <span class="ot">&lt;-</span> airbnb <span class="sc">%&gt;%</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Barrio) <span class="sc">%&gt;%</span></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">NumeroEntradas =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(NumeroEntradas)) <span class="sc">%&gt;%</span></span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>)</span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear una gráfica de barras para los 5 barrios con más entradas</span></span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(conteo_barrios, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Barrio, NumeroEntradas), <span class="at">y =</span> NumeroEntradas)) <span class="sc">+</span></span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Top 5 Barrios con Mayor Número de Entradas en Airbnb"</span>,</span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Barrio"</span>,</span>
<span id="cb51-17"><a href="#cb51-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Número de Entradas"</span>) <span class="sc">+</span></span>
<span id="cb51-18"><a href="#cb51-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="co"># Girar la gráfica para una mejor visualización</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="0-PracticaFinal_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<ol start="9" type="1">
<li>¿Cuantos Tipos de Alquiler diferentes hay? ¿Cuales son? ¿Cuantas entradas en el dataframe hay por cada tipo?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Asegúrate de que la columna TipoAlquiler sea de tipo string</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>TipoAlquiler <span class="ot">&lt;-</span> <span class="fu">as.character</span>(airbnb<span class="sc">$</span>TipoAlquiler)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Contar y listar los tipos de alquiler diferentes</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>tipos_alquiler_unicos <span class="ot">&lt;-</span> <span class="fu">unique</span>(airbnb<span class="sc">$</span>TipoAlquiler)</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>numero_tipos_alquiler <span class="ot">&lt;-</span> <span class="fu">length</span>(tipos_alquiler_unicos)</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Contar las entradas en el dataframe para cada tipo de alquiler</span></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>conteo_tipos_alquiler <span class="ot">&lt;-</span> <span class="fu">table</span>(airbnb<span class="sc">$</span>TipoAlquiler)</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar la información</span></span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Número de tipos de alquiler diferentes:"</span>, numero_tipos_alquiler))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Número de tipos de alquiler diferentes: 3"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Tipos de alquiler únicos:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Tipos de alquiler únicos:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(tipos_alquiler_unicos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Private room"    "Entire home/apt" "Shared room"    </code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Número de entradas por tipo de alquiler:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Número de entradas por tipo de alquiler:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conteo_tipos_alquiler)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Entire home/apt    Private room     Shared room 
           7903            5113             191 </code></pre>
</div>
</div>
<p>Muestra el diagrama de cajas del precio para cada uno de los diferentes Tipos de Alquiler</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Excluir filas con valores no finitos en la columna Precio</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>airbnb_limpio <span class="ot">&lt;-</span> <span class="fu">subset</span>(airbnb, <span class="sc">!</span><span class="fu">is.na</span>(Precio) <span class="sc">&amp;</span> Precio <span class="sc">!=</span> <span class="cn">Inf</span> <span class="sc">&amp;</span> Precio <span class="sc">!=</span> <span class="sc">-</span><span class="cn">Inf</span>)</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un diagrama de cajas del precio para cada tipo de alquiler con datos limpios</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(airbnb_limpio, <span class="fu">aes</span>(<span class="at">x =</span> TipoAlquiler, <span class="at">y =</span> Precio)) <span class="sc">+</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Diagrama de Cajas del Precio para Cada Tipo de Alquiler"</span>,</span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Tipo de Alquiler"</span>,</span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Precio"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="0-PracticaFinal_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<ol start="10" type="1">
<li>Cual es el precio medio de alquiler de cada uno, la diferencia que hay ¿es estadísticamente significativa? ¿Con que test lo comprobarías?</li>
</ol>
<p>Si la diferencia en el precio medio de alquiler entre los diferentes tipos de alquiler es estadísticamente significativa, podemos realizar un test ANOVA o Kruskal-Wallis. El test a utilizar depende de la distribución de los datos. Si los datos cumplen con los supuestos de ANOVA (normalidad y homogeneidad de varianzas), se puede utilizar ANOVA. Si los datos no cumplen con los supuestos de ANOVA, se puede utilizar Kruskal-Wallis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Asegúrate de que las columnas estén en el formato correcto</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>TipoAlquiler <span class="ot">&lt;-</span> <span class="fu">as.character</span>(airbnb<span class="sc">$</span>TipoAlquiler)</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>Precio <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(airbnb<span class="sc">$</span>Precio)</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular el precio medio de alquiler para cada tipo</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>precios_medios <span class="ot">&lt;-</span> airbnb <span class="sc">%&gt;%</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TipoAlquiler) <span class="sc">%&gt;%</span></span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">PrecioMedio =</span> <span class="fu">mean</span>(Precio, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Precio medio de alquiler por tipo:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Precio medio de alquiler por tipo:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(precios_medios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  TipoAlquiler    PrecioMedio
  &lt;chr&gt;                 &lt;dbl&gt;
1 Entire home/apt        87.3
2 Private room           34.3
3 Shared room            29.9</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Realizar un test ANOVA o Kruskal-Wallis para comparar las medias</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="co"># El test a utilizar depende de la distribución de los datos</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Ejemplo con ANOVA:</span></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>resultados_anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(Precio <span class="sc">~</span> TipoAlquiler, <span class="at">data =</span> airbnb)</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(resultados_anova))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Df   Sum Sq Mean Sq F value Pr(&gt;F)    
TipoAlquiler     2  8981217 4490608    1828 &lt;2e-16 ***
Residuals    13195 32417217    2457                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
9 observations deleted due to missingness</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Si los datos no cumplen con los supuestos de ANOVA, usar Kruskal-Wallis</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="co"># resultados_kruskal &lt;- kruskal.test(Precio ~ TipoAlquiler, data = airbnb)</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a><span class="co"># print(resultados_kruskal)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<ol start="11" type="1">
<li>Filtra el dataframe cuyos tipo de alquiler sea ‘Entire home/apt’ y guardalo en un dataframe llamado <em>airbnb_entire</em>. Estas serán las entradas que tienen un alquiler del piso completo.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar el DataFrame para entradas donde el tipo de alquiler es 'Entire home/apt'</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>airbnb_entire <span class="ot">&lt;-</span> <span class="fu">subset</span>(airbnb, TipoAlquiler <span class="sc">==</span> <span class="st">'Entire home/apt'</span>)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar las primeras filas del nuevo DataFrame</span></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airbnb_entire)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  CodigoPostal      Barrio TipoPropiedad    TipoAlquiler MaxOcupantes NumBanyos
2        28004 Universidad     Apartment Entire home/apt            6         1
3        28004 Universidad     Apartment Entire home/apt            3         1
4        28004 Universidad          Loft Entire home/apt            3         2
5        28015 Universidad     Apartment Entire home/apt            5         1
6        28004 Universidad     Apartment Entire home/apt            2         1
8        28004 Universidad     Apartment Entire home/apt            3         1
  NumDormitorios NumCamas TipoCama
2              3        5 Real Bed
3              2        2 Real Bed
4              1        1 Real Bed
5              1        1 Real Bed
6              0        1 Real Bed
8              1       NA Real Bed
                                                                                                                                                                                                                                                                                                                                                       Comodidades
2                                                                                                                                                                                      TV,Internet,Wireless Internet,Air conditioning,Kitchen,Indoor fireplace,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,Essentials,Shampoo
3                                                                                                                                                                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Doorman,Heating,Family/kid friendly,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace
4                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Pets allowed,Breakfast,Elevator in building,Indoor fireplace,Buzzer/wireless intercom,Heating,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace,translation missing: en.hosting_amenity_49,translation missing: en.hosting_amenity_50
5                                                                                                                                                                                                               TV,Wireless Internet,Air conditioning,Kitchen,Smoking allowed,Pets allowed,Elevator in building,Heating,Family/kid friendly,Washer,Essentials,Iron
6 TV,Cable TV,Internet,Wireless Internet,Air conditioning,Wheelchair accessible,Kitchen,Doorman,Elevator in building,Buzzer/wireless intercom,Heating,Washer,Smoke detector,Carbon monoxide detector,First aid kit,Safety card,Fire extinguisher,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace,Self Check-In,Doorman Entry
8                                                                                                                                                                                                                                                       TV,Wireless Internet,Air conditioning,Kitchen,Elevator in building,Buzzer/wireless intercom,Heating,Washer
  PiesCuadrados Precio Puntuacion MetrosCuadrados
2            NA     92         96              NA
3            NA     55         91              NA
4            NA     60        100              NA
5           538     75         90        49.98181
6            NA     55         95              NA
8            NA     70         84              NA</code></pre>
</div>
</div>
<hr>
<ol start="12" type="1">
<li>¿Cuales son los 5 barrios que tienen un mayor número de apartamentos enteros en alquiler? Nota: Mirar solo en airbnb_entire. A partir de este punto y hasta que se diga lo contrario partiremos de airbnb_entire.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Asegúrate de que la columna Barrio sea de tipo string</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>airbnb_entire<span class="sc">$</span>Barrio <span class="ot">&lt;-</span> <span class="fu">as.character</span>(airbnb_entire<span class="sc">$</span>Barrio)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Contar las entradas en cada barrio</span></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>conteo_barrios <span class="ot">&lt;-</span> <span class="fu">table</span>(airbnb_entire<span class="sc">$</span>Barrio)</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Ordenar los conteos de mayor a menor y seleccionar los 5 barrios con más entradas</span></span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>top_5_barrios <span class="ot">&lt;-</span> <span class="fu">sort</span>(conteo_barrios, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar los resultados</span></span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Los 5 barrios con mayor número de apartamentos enteros en alquiler son:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Los 5 barrios con mayor número de apartamentos enteros en alquiler son:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(top_5_barrios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Embajadores Universidad     Palacio         Sol      Cortes 
       1228         984         769         701         574 </code></pre>
</div>
</div>
<hr>
<ol start="13" type="1">
<li>¿Cuales son los 5 barrios que tienen un mayor precio medio de alquiler para apartamentos enteros (es decir, del dataframe airbnb_entire)? ¿Cual es su precio medio?</li>
</ol>
<p>Ayuda: Usa la función aggregate <code>aggregate(.~colname,df,mean,na.rm=TRUE)</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Asegúrate de que las columnas estén en el formato correcto</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>airbnb_entire<span class="sc">$</span>Barrio <span class="ot">&lt;-</span> <span class="fu">as.character</span>(airbnb_entire<span class="sc">$</span>Barrio)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>airbnb_entire<span class="sc">$</span>Precio <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(airbnb_entire<span class="sc">$</span>Precio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Usar aggregate para calcular el precio medio por barrio</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>precio_medio_por_barrio <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(Precio <span class="sc">~</span> Barrio, airbnb_entire, mean, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>top_5_barrios_precio_medio <span class="ot">&lt;-</span> <span class="fu">head</span>(precio_medio_por_barrio[<span class="fu">order</span>(precio_medio_por_barrio<span class="sc">$</span>Precio, <span class="at">decreasing =</span> <span class="cn">TRUE</span>), ], <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Los 5 barrios con el mayor precio medio de alquiler para apartamentos enteros son:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Los 5 barrios con el mayor precio medio de alquiler para apartamentos enteros son:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(top_5_barrios_precio_medio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Barrio   Precio
77       Palomas 309.7500
50 Fuentelareina 180.0000
93     Recoletos 161.9254
43    El Plantío 150.0000
30    Castellana 141.3889</code></pre>
</div>
</div>
<hr>
<ol start="14" type="1">
<li>¿Cuantos apartamentos hay en cada uno de esos barrios?</li>
</ol>
<p>Mostrar una dataframe con el nombre del barrio, el precio y el número de entradas.</p>
<p>Ayuda: Podeis crear un nuevo dataframe con las columnas “Barrio” y “Freq” que contenga el número de entradas en cada barrio y hacer un merge con el dataframe del punto anterior.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Contar las entradas (apartamentos) en cada uno de los 5 barrios superiores</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>conteo_apartamentos_top5 <span class="ot">&lt;-</span> airbnb_entire <span class="sc">%&gt;%</span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Barrio <span class="sc">%in%</span> top_5_barrios_precio_medio<span class="sc">$</span>Barrio) <span class="sc">%&gt;%</span></span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Barrio) <span class="sc">%&gt;%</span></span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Freq =</span> <span class="fu">n</span>())</span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar el conteo de apartamentos</span></span>
<span id="cb83-8"><a href="#cb83-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Número de apartamentos en los 5 barrios con mayor precio medio:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Número de apartamentos en los 5 barrios con mayor precio medio:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conteo_apartamentos_top5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  Barrio         Freq
  &lt;chr&gt;         &lt;int&gt;
1 Castellana       73
2 El Plantío        1
3 Fuentelareina     2
4 Palomas           4
5 Recoletos       135</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fusionar el conteo de apartamentos con el precio medio por barrio</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>informacion_detallada <span class="ot">&lt;-</span> <span class="fu">merge</span>(top_5_barrios_precio_medio, conteo_apartamentos_top5, <span class="at">by =</span> <span class="st">"Barrio"</span>)</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar el DataFrame final</span></span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Información detallada de los 5 barrios con mayor precio medio:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Información detallada de los 5 barrios con mayor precio medio:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(informacion_detallada)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Barrio   Precio Freq
1    Castellana 141.3889   73
2    El Plantío 150.0000    1
3 Fuentelareina 180.0000    2
4       Palomas 309.7500    4
5     Recoletos 161.9254  135</code></pre>
</div>
</div>
<hr>
<ol start="15" type="1">
<li>Partiendo del dataframe anterior, muestra los 5 barrios con mayor precio, pero que tengan más de 100 entradas de alquiler.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Contar las entradas en cada barrio</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>conteo_barrios <span class="ot">&lt;-</span> airbnb_entire <span class="sc">%&gt;%</span></span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Barrio) <span class="sc">%&gt;%</span></span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">NumeroEntradas =</span> <span class="fu">n</span>())</span>
<span id="cb91-5"><a href="#cb91-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb91-6"><a href="#cb91-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar los barrios con más de 100 entradas</span></span>
<span id="cb91-7"><a href="#cb91-7" aria-hidden="true" tabindex="-1"></a>barrios_mas_100_entradas <span class="ot">&lt;-</span> conteo_barrios[conteo_barrios<span class="sc">$</span>NumeroEntradas <span class="sc">&gt;</span> <span class="dv">100</span>, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular el precio medio de alquiler para cada barrio</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>precio_medio_por_barrio <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(Precio <span class="sc">~</span> Barrio, airbnb_entire, mean, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Fusionar con los barrios que tienen más de 100 entradas</span></span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>barrios_filtrados <span class="ot">&lt;-</span> <span class="fu">merge</span>(barrios_mas_100_entradas, precio_medio_por_barrio, <span class="at">by =</span> <span class="st">"Barrio"</span>)</span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-7"><a href="#cb92-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Ordenar por precio medio y seleccionar los 5 primeros</span></span>
<span id="cb92-8"><a href="#cb92-8" aria-hidden="true" tabindex="-1"></a>top_5_barrios_precio_mas_100_entradas <span class="ot">&lt;-</span> <span class="fu">head</span>(barrios_filtrados[<span class="fu">order</span>(barrios_filtrados<span class="sc">$</span>Precio, <span class="at">decreasing =</span> <span class="cn">TRUE</span>), ], <span class="dv">5</span>)</span>
<span id="cb92-9"><a href="#cb92-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-10"><a href="#cb92-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar los resultados</span></span>
<span id="cb92-11"><a href="#cb92-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Los 5 barrios con mayor precio medio y más de 100 entradas son:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Los 5 barrios con mayor precio medio y más de 100 entradas son:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(top_5_barrios_precio_mas_100_entradas)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Barrio NumeroEntradas    Precio
8  Recoletos            135 161.92537
4       Goya            142 111.33803
9        Sol            701 100.75036
10 Trafalgar            223  98.57848
5   Justicia            534  98.25468</code></pre>
</div>
</div>
<hr>
<ol start="16" type="1">
<li>Dibuja el diagrama de densidad de distribución de los diferentes precios. Serían 5 gráficas, una por cada barrio.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Asegúrate de que las columnas estén en el formato correcto</span></span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>airbnb_entire<span class="sc">$</span>Barrio <span class="ot">&lt;-</span> <span class="fu">as.character</span>(airbnb_entire<span class="sc">$</span>Barrio)</span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>airbnb_entire<span class="sc">$</span>Precio <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(airbnb_entire<span class="sc">$</span>Precio)</span>
<span id="cb96-5"><a href="#cb96-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-6"><a href="#cb96-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar el DataFrame para excluir valores no finitos en la columna Precio</span></span>
<span id="cb96-7"><a href="#cb96-7" aria-hidden="true" tabindex="-1"></a>datos_filtrados <span class="ot">&lt;-</span> <span class="fu">subset</span>(airbnb_entire, <span class="sc">!</span><span class="fu">is.na</span>(Precio) <span class="sc">&amp;</span> Precio <span class="sc">!=</span> <span class="cn">Inf</span> <span class="sc">&amp;</span> Precio <span class="sc">!=</span> <span class="sc">-</span><span class="cn">Inf</span> <span class="sc">&amp;</span> Barrio <span class="sc">%in%</span> top_5_barrios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<ol start="17" type="1">
<li>Calcula el tamaño medio, en metros cuadrados, para los 5 barrios anteriores y muestralo en el mismo dataframe junto con el precio y número de entradas</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Asegurándonos de que top_5_barrios contiene los barrios correctos</span></span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Esta línea ya está en tu código, asegúrate de que se ejecuta correctamente.</span></span>
<span id="cb97-5"><a href="#cb97-5" aria-hidden="true" tabindex="-1"></a>top_5_barrios <span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">sort</span>(<span class="fu">table</span>(airbnb_entire<span class="sc">$</span>Barrio), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>])</span>
<span id="cb97-6"><a href="#cb97-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-7"><a href="#cb97-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar para incluir solo los top 5 barrios</span></span>
<span id="cb97-8"><a href="#cb97-8" aria-hidden="true" tabindex="-1"></a>datos_filtrados <span class="ot">&lt;-</span> airbnb_entire <span class="sc">%&gt;%</span> </span>
<span id="cb97-9"><a href="#cb97-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Barrio <span class="sc">%in%</span> top_5_barrios)</span>
<span id="cb97-10"><a href="#cb97-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-11"><a href="#cb97-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular el precio medio, tamaño medio y número de entradas por barrio</span></span>
<span id="cb97-12"><a href="#cb97-12" aria-hidden="true" tabindex="-1"></a>resumen_barrios <span class="ot">&lt;-</span> datos_filtrados <span class="sc">%&gt;%</span></span>
<span id="cb97-13"><a href="#cb97-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Barrio) <span class="sc">%&gt;%</span></span>
<span id="cb97-14"><a href="#cb97-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb97-15"><a href="#cb97-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">PrecioMedio =</span> <span class="fu">mean</span>(Precio, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb97-16"><a href="#cb97-16" aria-hidden="true" tabindex="-1"></a>    TamañoMedioM2 <span class="ot">=</span> <span class="fu">mean</span>(MetrosCuadrados, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb97-17"><a href="#cb97-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">NumeroEntradas =</span> <span class="fu">n</span>()</span>
<span id="cb97-18"><a href="#cb97-18" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb97-19"><a href="#cb97-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-20"><a href="#cb97-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar el resumen</span></span>
<span id="cb97-21"><a href="#cb97-21" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(resumen_barrios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 4
  Barrio      PrecioMedio TamañoMedioM2 NumeroEntradas
  &lt;chr&gt;             &lt;dbl&gt;         &lt;dbl&gt;          &lt;int&gt;
1 Cortes             94.4          14.0            574
2 Embajadores        73.7          27.7           1228
3 Palacio            93.3          29.7            769
4 Sol               101.           45.6            701
5 Universidad        79.4          32.8            984</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Asegúrate de que las columnas estén en el formato correcto</span></span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a>airbnb_entire<span class="sc">$</span>Barrio <span class="ot">&lt;-</span> <span class="fu">as.character</span>(airbnb_entire<span class="sc">$</span>Barrio)</span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a>airbnb_entire<span class="sc">$</span>Precio <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(airbnb_entire<span class="sc">$</span>Precio)</span>
<span id="cb99-6"><a href="#cb99-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-7"><a href="#cb99-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Asegúrate de filtrar el dataframe para incluir solo los top 5 barrios y excluir valores no finitos</span></span>
<span id="cb99-8"><a href="#cb99-8" aria-hidden="true" tabindex="-1"></a>datos_filtrados <span class="ot">&lt;-</span> <span class="fu">subset</span>(airbnb_entire, <span class="sc">!</span><span class="fu">is.na</span>(Precio) <span class="sc">&amp;</span> Precio <span class="sc">!=</span> <span class="cn">Inf</span> <span class="sc">&amp;</span> Precio <span class="sc">!=</span> <span class="sc">-</span><span class="cn">Inf</span> <span class="sc">&amp;</span> Barrio <span class="sc">%in%</span> top_5_barrios)</span>
<span id="cb99-9"><a href="#cb99-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-10"><a href="#cb99-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un diagrama de densidad para cada barrio con datos filtrados</span></span>
<span id="cb99-11"><a href="#cb99-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datos_filtrados, <span class="fu">aes</span>(<span class="at">x =</span> Precio, <span class="at">fill =</span> Barrio)) <span class="sc">+</span></span>
<span id="cb99-12"><a href="#cb99-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb99-13"><a href="#cb99-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Barrio, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span>  <span class="co"># Usar `scales = "free"` para permitir diferentes escalas en los ejes Y</span></span>
<span id="cb99-14"><a href="#cb99-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb99-15"><a href="#cb99-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución de los Precios por Barrio"</span>,</span>
<span id="cb99-16"><a href="#cb99-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Precio"</span>,</span>
<span id="cb99-17"><a href="#cb99-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Densidad"</span>) <span class="sc">+</span></span>
<span id="cb99-18"><a href="#cb99-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="0-PracticaFinal_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<ol start="18" type="1">
<li>Dibuja el diagrama de densidad de distribución de los diferentes tamaños de apartamentos. Serían 5 gráficas, una por cada barrio.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-4"><a href="#cb100-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Asegúrate de que las columnas estén en el formato correcto</span></span>
<span id="cb100-5"><a href="#cb100-5" aria-hidden="true" tabindex="-1"></a>airbnb_entire<span class="sc">$</span>Barrio <span class="ot">&lt;-</span> <span class="fu">as.character</span>(airbnb_entire<span class="sc">$</span>Barrio)</span>
<span id="cb100-6"><a href="#cb100-6" aria-hidden="true" tabindex="-1"></a>airbnb_entire<span class="sc">$</span>MetrosCuadrados <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(airbnb_entire<span class="sc">$</span>MetrosCuadrados)</span>
<span id="cb100-7"><a href="#cb100-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-8"><a href="#cb100-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Identificar los top 5 barrios por alguna métrica, por ejemplo, número de listados</span></span>
<span id="cb100-9"><a href="#cb100-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Si ya tienes identificados tus top_5_barrios, asegúrate de que esta línea refleje correctamente esos barrios</span></span>
<span id="cb100-10"><a href="#cb100-10" aria-hidden="true" tabindex="-1"></a>top_5_barrios <span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">sort</span>(<span class="fu">table</span>(airbnb_entire<span class="sc">$</span>Barrio), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>])</span>
<span id="cb100-11"><a href="#cb100-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-12"><a href="#cb100-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar el DataFrame para incluir solo los top 5 barrios y excluir valores no finitos en la columna de tamaño</span></span>
<span id="cb100-13"><a href="#cb100-13" aria-hidden="true" tabindex="-1"></a>datos_filtrados <span class="ot">&lt;-</span> airbnb_entire <span class="sc">%&gt;%</span></span>
<span id="cb100-14"><a href="#cb100-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Barrio <span class="sc">%in%</span> top_5_barrios <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(MetrosCuadrados) <span class="sc">&amp;</span> MetrosCuadrados <span class="sc">!=</span> <span class="cn">Inf</span> <span class="sc">&amp;</span> MetrosCuadrados <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb100-15"><a href="#cb100-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-16"><a href="#cb100-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un diagrama de densidad para cada barrio con datos filtrados</span></span>
<span id="cb100-17"><a href="#cb100-17" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datos_filtrados, <span class="fu">aes</span>(<span class="at">x =</span> MetrosCuadrados, <span class="at">fill =</span> Barrio)) <span class="sc">+</span></span>
<span id="cb100-18"><a href="#cb100-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb100-19"><a href="#cb100-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Barrio, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb100-20"><a href="#cb100-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb100-21"><a href="#cb100-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución del Tamaño de los Apartamentos por Barrio"</span>,</span>
<span id="cb100-22"><a href="#cb100-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Tamaño (Metros Cuadrados)"</span>,</span>
<span id="cb100-23"><a href="#cb100-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Densidad"</span>) <span class="sc">+</span></span>
<span id="cb100-24"><a href="#cb100-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="0-PracticaFinal_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<ol start="19" type="1">
<li>Esta claro que las medias de metros cuadrados de cada uno de estos 5 barrios parecen ser diferentes, pero</li>
</ol>
<p>¿son estadísticamente diferentes?</p>
<p>Los resultados de las pruebas estadísticas que has realizado proporcionan información valiosa sobre las diferencias en el tamaño de los apartamentos entre los cinco barrios seleccionados. Aquí está un análisis detallado de estos resultados:</p>
<p>Pruebas de Shapiro-Wilk para Normalidad:</p>
<p>Los resultados muestran que los tamaños de los apartamentos en la mayoría de los barrios seleccionados no siguen una distribución normal, excepto en el barrio “Goya” (p = 0.5199 &gt; 0.05, indicando normalidad). En “Sol”, “Justicia”, “Recoletos” y “Trafalgar”, los valores p son significativamente bajos, sugiriendo que los datos no se distribuyen normalmente. Prueba de Levene para Homogeneidad de Varianzas:</p>
<p>El test de Levene no muestra diferencias significativas en las varianzas entre los grupos (p = 0.2673 &gt; 0.05), lo que sugiere que las varianzas son homogéneas. Test ANOVA:</p>
<p>A pesar de la homogeneidad de varianzas, el valor p del ANOVA (p = 0.637 &gt; 0.05) indica que no hay diferencias estadísticamente significativas en las medias de los tamaños de los apartamentos entre los cinco barrios. Test de Kruskal-Wallis:</p>
<p>Dado que los datos no siguen una distribución normal en la mayoría de los barrios, el test de Kruskal-Wallis es más apropiado. El test de Kruskal-Wallis también indica que no hay diferencias estadísticamente significativas en las medias de los tamaños de los apartamentos entre los cinco barrios (p = 0.7574 &gt; 0.05). Conclusiones: La falta de normalidad en los tamaños de los apartamentos en la mayoría de los barrios sugiere la necesidad de utilizar métodos no paramétricos como el test de Kruskal-Wallis. Tanto el ANOVA como el test de Kruskal-Wallis concluyen que no hay diferencias significativas en las medias de los tamaños de los apartamentos entre los cinco barrios seleccionados. Esto implica que, aunque los barrios pueden tener características distintas que afectan el precio medio, el tamaño de los apartamentos no varía significativamente entre estos barrios desde un punto de vista estadístico. Estos resultados son importantes para entender cómo el tamaño de los apartamentos contribuye a la dinámica del mercado inmobiliario en estos barrios y pueden informar decisiones relacionadas con inversiones inmobiliarias o estrategias de precios.</p>
<p>¿Que test habría que usar para comprobarlo?</p>
<p>Consideraciones para Elegir el Test Adecuado Normalidad de los Datos:</p>
<p>Si los datos son normalmente distribuidos en cada grupo, se pueden considerar pruebas paramétricas como el ANOVA (Análisis de Varianza). Si los datos no siguen una distribución normal, deberíamos optar por pruebas no paramétricas como el test de Kruskal-Wallis. Homogeneidad de las Varianzas:</p>
<p>Si las varianzas son homogéneas (iguales entre los grupos), el ANOVA es adecuado. Si las varianzas no son homogéneas, incluso con datos normalmente distribuidos, se puede considerar el uso de Welch’s ANOVA o métodos no paramétricos.</p>
<p>Pasos para el Análisis Prueba de Normalidad:</p>
<p>Se puede realizar una prueba de Shapiro-Wilk o una prueba de normalidad gráfica (por ejemplo, QQ plots) para cada grupo. Prueba de Homogeneidad de Varianzas:</p>
<p>Utilizar la prueba de Levene o Bartlett para evaluar si las varianzas son homogéneas. Ejecutar el Test Adecuado:</p>
<p>Si los datos pasan las pruebas de normalidad y homogeneidad de varianzas, ejecutar un ANOVA. Si no, optar por Kruskal-Wallis o Welch’s ANOVA.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car) <span class="co"># Para la prueba de Levene para homogeneidad de varianzas</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 'datos_top_5_barrios' debe ser un dataframe que contenga solo los datos de los top 5 barrios</span></span>
<span id="cb105-4"><a href="#cb105-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Debe incluir las columnas 'Barrio' y 'MetrosCuadrados' correctamente formateadas</span></span>
<span id="cb105-5"><a href="#cb105-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-6"><a href="#cb105-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Aplicar la prueba de Shapiro-Wilk a cada uno de los 5 barrios</span></span>
<span id="cb105-7"><a href="#cb105-7" aria-hidden="true" tabindex="-1"></a>datos_top_5_barrios <span class="ot">&lt;-</span> datos_filtrados <span class="co"># Asegúrate de que esta variable contenga los datos correctos</span></span>
<span id="cb105-8"><a href="#cb105-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-9"><a href="#cb105-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Pruebas de Shapiro-Wilk para Normalidad"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Pruebas de Shapiro-Wilk para Normalidad"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(barrio <span class="cf">in</span> <span class="fu">unique</span>(datos_top_5_barrios<span class="sc">$</span>Barrio)) {</span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Prueba de Shapiro-Wilk para"</span>, barrio, <span class="st">":"</span>))</span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a>  datos_barrio <span class="ot">&lt;-</span> <span class="fu">filter</span>(datos_top_5_barrios, Barrio <span class="sc">==</span> barrio)</span>
<span id="cb107-4"><a href="#cb107-4" aria-hidden="true" tabindex="-1"></a>  test <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(datos_barrio<span class="sc">$</span>MetrosCuadrados)</span>
<span id="cb107-5"><a href="#cb107-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(test)</span>
<span id="cb107-6"><a href="#cb107-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Prueba de Shapiro-Wilk para Universidad :"

    Shapiro-Wilk normality test

data:  datos_barrio$MetrosCuadrados
W = 0.9345, p-value = 0.03814

[1] "Prueba de Shapiro-Wilk para Sol :"

    Shapiro-Wilk normality test

data:  datos_barrio$MetrosCuadrados
W = 0.90899, p-value = 0.003528

[1] "Prueba de Shapiro-Wilk para Embajadores :"

    Shapiro-Wilk normality test

data:  datos_barrio$MetrosCuadrados
W = 0.9753, p-value = 0.5865

[1] "Prueba de Shapiro-Wilk para Cortes :"

    Shapiro-Wilk normality test

data:  datos_barrio$MetrosCuadrados
W = 0.87865, p-value = 0.0556

[1] "Prueba de Shapiro-Wilk para Palacio :"

    Shapiro-Wilk normality test

data:  datos_barrio$MetrosCuadrados
W = 0.86348, p-value = 0.01121</code></pre>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prueba de Levene para Homogeneidad de Varianzas</span></span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Prueba de Levene para Homogeneidad de Varianzas:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Prueba de Levene para Homogeneidad de Varianzas:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>levene_test <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">leveneTest</span>(MetrosCuadrados <span class="sc">~</span> Barrio, <span class="at">data =</span> datos_top_5_barrios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in leveneTest.default(y = y, group = group, ...): group coerced to
factor.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(levene_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
       Df F value   Pr(&gt;F)   
group   4  3.8114 0.005685 **
      139                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Realizar el test ANOVA</span></span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Test ANOVA para diferencias en Metros Cuadrados entre Barrios:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Test ANOVA para diferencias en Metros Cuadrados entre Barrios:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a>anova_result <span class="ot">&lt;-</span> <span class="fu">aov</span>(MetrosCuadrados <span class="sc">~</span> Barrio, <span class="at">data =</span> datos_top_5_barrios)</span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(anova_result))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)   
Barrio        4  19952    4988   3.986 0.0043 **
Residuals   139 173959    1252                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<hr>
<p>Para únicamente los pisos de alquiler en el barrio de Sol:</p>
<p><code>barrio_sol&lt;-subset(airbnb_entire,Barrio=="Sol")</code></p>
<p>Calcular un modelo lineal que combine alguna de estas variables: * NumBanyos * NumDormitorios * MaxOcupantes * MetrosCuadrados</p>
<ol start="20" type="1">
<li>Primero calculamos la correlación para ver como se relacionan estas variables entre sí.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar los datos para el barrio de Sol</span></span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a>barrio_sol <span class="ot">&lt;-</span> <span class="fu">subset</span>(airbnb_entire, Barrio <span class="sc">==</span> <span class="st">"Sol"</span>)</span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-4"><a href="#cb119-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Asegúrate de que las columnas estén en el formato correcto</span></span>
<span id="cb119-5"><a href="#cb119-5" aria-hidden="true" tabindex="-1"></a>barrio_sol<span class="sc">$</span>NumBanyos <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(barrio_sol<span class="sc">$</span>NumBanyos)</span>
<span id="cb119-6"><a href="#cb119-6" aria-hidden="true" tabindex="-1"></a>barrio_sol<span class="sc">$</span>NumDormitorios <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(barrio_sol<span class="sc">$</span>NumDormitorios)</span>
<span id="cb119-7"><a href="#cb119-7" aria-hidden="true" tabindex="-1"></a>barrio_sol<span class="sc">$</span>MaxOcupantes <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(barrio_sol<span class="sc">$</span>MaxOcupantes)</span>
<span id="cb119-8"><a href="#cb119-8" aria-hidden="true" tabindex="-1"></a>barrio_sol<span class="sc">$</span>MetrosCuadrados <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(barrio_sol<span class="sc">$</span>MetrosCuadrados)</span>
<span id="cb119-9"><a href="#cb119-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-10"><a href="#cb119-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular la matriz de correlación para las variables seleccionadas</span></span>
<span id="cb119-11"><a href="#cb119-11" aria-hidden="true" tabindex="-1"></a>matriz_correlacion <span class="ot">&lt;-</span> <span class="fu">cor</span>(barrio_sol[,<span class="fu">c</span>(<span class="st">"NumBanyos"</span>, <span class="st">"NumDormitorios"</span>, <span class="st">"MaxOcupantes"</span>, <span class="st">"MetrosCuadrados"</span>)], <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb119-12"><a href="#cb119-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-13"><a href="#cb119-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar la matriz de correlación</span></span>
<span id="cb119-14"><a href="#cb119-14" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Matriz de correlación entre las variables seleccionadas:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Matriz de correlación entre las variables seleccionadas:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(matriz_correlacion)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                NumBanyos NumDormitorios MaxOcupantes MetrosCuadrados
NumBanyos       1.0000000      0.6873719    0.7017290       0.4820549
NumDormitorios  0.6873719      1.0000000    0.7853809       0.5684521
MaxOcupantes    0.7017290      0.7853809    1.0000000       0.4286233
MetrosCuadrados 0.4820549      0.5684521    0.4286233       1.0000000</code></pre>
</div>
</div>
<hr>
<ol start="21" type="1">
<li>Se observa que la correlación entre el número de dormitorios y los metros cuadrados es sorprendentemente baja. ¿Son de fiar esos números?</li>
</ol>
<p>Mediante un histograma o curvas de densidad podemos descartar números que notienen sentido en el dataframe barrio_sol, para tener una matriz de correlación que tenga mayor sentido.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Limpiar los datos: eliminar filas con valores NA o atípicos</span></span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a>barrio_sol <span class="ot">&lt;-</span> <span class="fu">subset</span>(barrio_sol, <span class="sc">!</span><span class="fu">is.na</span>(NumDormitorios) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(MetrosCuadrados))</span>
<span id="cb123-3"><a href="#cb123-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Aquí puedes añadir más condiciones para tratar valores atípicos si es necesario</span></span>
<span id="cb123-4"><a href="#cb123-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-5"><a href="#cb123-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear histograma para NumDormitorios</span></span>
<span id="cb123-6"><a href="#cb123-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(barrio_sol, <span class="fu">aes</span>(<span class="at">x =</span> NumDormitorios)) <span class="sc">+</span></span>
<span id="cb123-7"><a href="#cb123-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">10</span>, <span class="at">fill =</span> <span class="st">"blue"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb123-8"><a href="#cb123-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución del Número de Dormitorios en el Barrio de Sol"</span>,</span>
<span id="cb123-9"><a href="#cb123-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Número de Dormitorios"</span>,</span>
<span id="cb123-10"><a href="#cb123-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>) <span class="sc">+</span></span>
<span id="cb123-11"><a href="#cb123-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="0-PracticaFinal_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear curva de densidad para MetrosCuadrados</span></span>
<span id="cb124-2"><a href="#cb124-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(barrio_sol, <span class="fu">aes</span>(<span class="at">x =</span> MetrosCuadrados)) <span class="sc">+</span></span>
<span id="cb124-3"><a href="#cb124-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"green"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb124-4"><a href="#cb124-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución de Metros Cuadrados en el Barrio de Sol"</span>,</span>
<span id="cb124-5"><a href="#cb124-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Metros Cuadrados"</span>,</span>
<span id="cb124-6"><a href="#cb124-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Densidad"</span>) <span class="sc">+</span></span>
<span id="cb124-7"><a href="#cb124-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="0-PracticaFinal_files/figure-html/unnamed-chunk-40-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
<ol start="22" type="1">
<li>Una vez que hayamos filtrado los datos correspondientes calcular el valor o la combinación de valores que mejor nos permite obtener el precio de un inmueble.</li>
</ol>
<p>¿Que variable es más fiable para conocer el precio de un inmueble, el número de habitaciones o los metros cuadrados?</p>
<p>Para determinar qué variable es más fiable para predecir el precio de un inmueble en el barrio de Sol, ya sea el número de habitaciones (<strong><code>NumDormitorios</code></strong>) o los metros cuadrados (<strong><code>MetrosCuadrados</code></strong>), podemos utilizar un análisis de regresión lineal. Este análisis nos permitirá evaluar la relación de cada una de estas variables con el precio del inmueble y determinar cuál de ellas tiene una mayor influencia.</p>
<section id="pasos-para-el-análisis-de-regresión-lineal" class="level3">
<h3 class="anchored" data-anchor-id="pasos-para-el-análisis-de-regresión-lineal"><strong>Pasos para el Análisis de Regresión Lineal</strong></h3>
<ol type="1">
<li><p><strong>Preparar los Datos:</strong></p>
<ul>
<li>Asegúrate de que los datos estén limpios y de que hayas filtrado o tratado los valores atípicos o faltantes.</li>
</ul></li>
<li><p><strong>Construir Modelos de Regresión Lineal:</strong></p>
<ul>
<li><p>Construye un modelo de regresión lineal con <strong><code>NumDormitorios</code></strong> como variable predictora y <strong><code>Precio</code></strong> como variable de respuesta.</p></li>
<li><p>Construye otro modelo con <strong><code>MetrosCuadrados</code></strong> como variable predictora y <strong><code>Precio</code></strong> como variable de respuesta.</p></li>
</ul></li>
<li><p><strong>Evaluar los Modelos:</strong></p>
<ul>
<li>Compara los coeficientes de determinación (R²) de ambos modelos. El modelo con un valor R² más alto será el que mejor explique la variación en el precio.</li>
</ul></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargar la librería necesaria para la regresión</span></span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: zoo</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'zoo'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    as.Date, as.Date.numeric</code></pre>
</div>
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo de regresión con NumDormitorios</span></span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a>modelo_dormitorios <span class="ot">&lt;-</span> <span class="fu">lm</span>(Precio <span class="sc">~</span> NumDormitorios, <span class="at">data =</span> barrio_sol)</span>
<span id="cb129-3"><a href="#cb129-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_dormitorios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Precio ~ NumDormitorios, data = barrio_sol)

Residuals:
    Min      1Q  Median      3Q     Max 
-93.239 -14.705  -6.205  14.714 104.473 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      50.527      7.554   6.689 9.73e-09 ***
NumDormitorios   30.678      3.927   7.812 1.26e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 35.33 on 58 degrees of freedom
Multiple R-squared:  0.5127,    Adjusted R-squared:  0.5043 
F-statistic: 61.03 on 1 and 58 DF,  p-value: 1.265e-10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo de regresión con MetrosCuadrados</span></span>
<span id="cb131-2"><a href="#cb131-2" aria-hidden="true" tabindex="-1"></a>modelo_metros <span class="ot">&lt;-</span> <span class="fu">lm</span>(Precio <span class="sc">~</span> MetrosCuadrados, <span class="at">data =</span> barrio_sol)</span>
<span id="cb131-3"><a href="#cb131-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_metros)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Precio ~ MetrosCuadrados, data = barrio_sol)

Residuals:
    Min      1Q  Median      3Q     Max 
-61.403 -25.126  -6.573  10.003 138.353 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     69.57277    6.70573  10.375 7.79e-15 ***
MetrosCuadrados  0.61367    0.09721   6.313 4.13e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 38.96 on 58 degrees of freedom
Multiple R-squared:  0.4073,    Adjusted R-squared:  0.397 
F-statistic: 39.85 on 1 and 58 DF,  p-value: 4.134e-08</code></pre>
</div>
</div>
<hr>
<ol start="23" type="1">
<li>Responde con su correspondiente margen de error del 95%, ¿cuantos euros incrementa el precio del alquiler por cada metro cuadrado extra del piso?</li>
</ol>
<p>El precio del alquiler por cada metro cuadrado extra del piso, con un margen de error del 95%, debemos referirnos al modelo de regresión lineal que relaciona los <strong><code>MetrosCuadrados</code></strong> con el <strong><code>Precio</code></strong>. En particular, necesitamos examinar el coeficiente de la variable <strong><code>MetrosCuadrados</code></strong> en este modelo, así como su intervalo de confianza.</p>
</section>
<section id="cálculo-del-coeficiente-y-su-intervalo-de-confianza" class="level3">
<h3 class="anchored" data-anchor-id="cálculo-del-coeficiente-y-su-intervalo-de-confianza"><strong>Cálculo del Coeficiente y su Intervalo de Confianza</strong></h3>
<ol type="1">
<li><p><strong>Extraer el Coeficiente:</strong></p>
<ul>
<li>El coeficiente de <strong><code>MetrosCuadrados</code></strong> en el modelo de regresión nos dirá cuánto cambia el precio en promedio por cada metro cuadrado adicional.</li>
</ul></li>
<li><p><strong>Calcular el Intervalo de Confianza del 95%:</strong></p>
<ul>
<li>El intervalo de confianza nos proporcionará un rango dentro del cual podemos estar razonablemente seguros de que se encuentra el verdadero valor del coeficiente.</li>
</ul></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extraer el coeficiente para MetrosCuadrados</span></span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a>coeficiente_metros <span class="ot">&lt;-</span> <span class="fu">coef</span>(modelo_metros)[<span class="st">"MetrosCuadrados"</span>]</span>
<span id="cb133-3"><a href="#cb133-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb133-4"><a href="#cb133-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular el intervalo de confianza del 95%</span></span>
<span id="cb133-5"><a href="#cb133-5" aria-hidden="true" tabindex="-1"></a>intervalo_confianza <span class="ot">&lt;-</span> <span class="fu">confint</span>(modelo_metros, <span class="st">"MetrosCuadrados"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb133-6"><a href="#cb133-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb133-7"><a href="#cb133-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar los resultados</span></span>
<span id="cb133-8"><a href="#cb133-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Incremento en el precio por cada metro cuadrado extra:"</span>, coeficiente_metros))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Incremento en el precio por cada metro cuadrado extra: 0.613673495951023"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Intervalo de confianza del 95% para el coeficiente:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Intervalo de confianza del 95% para el coeficiente:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(intervalo_confianza)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    2.5 %    97.5 %
MetrosCuadrados 0.4190858 0.8082612</code></pre>
</div>
</div>
<hr>
<ol start="24" type="1">
<li>Responde con su correspondiente margen de error del 95%, ¿cuantos euros incrementa el precio del alquiler por cada habitación?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Asumiendo que ya tienes el modelo de regresión creado</span></span>
<span id="cb139-2"><a href="#cb139-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo: modelo_dormitorios &lt;- lm(Precio ~ NumDormitorios, data = barrio_sol)</span></span>
<span id="cb139-3"><a href="#cb139-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb139-4"><a href="#cb139-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Extraer el coeficiente para NumDormitorios</span></span>
<span id="cb139-5"><a href="#cb139-5" aria-hidden="true" tabindex="-1"></a>coeficiente_dormitorios <span class="ot">&lt;-</span> <span class="fu">coef</span>(modelo_dormitorios)[<span class="st">"NumDormitorios"</span>]</span>
<span id="cb139-6"><a href="#cb139-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb139-7"><a href="#cb139-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular el intervalo de confianza del 95%</span></span>
<span id="cb139-8"><a href="#cb139-8" aria-hidden="true" tabindex="-1"></a>intervalo_confianza_dormitorios <span class="ot">&lt;-</span> <span class="fu">confint</span>(modelo_dormitorios, <span class="st">"NumDormitorios"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb139-9"><a href="#cb139-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb139-10"><a href="#cb139-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar los resultados</span></span>
<span id="cb139-11"><a href="#cb139-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Incremento en el precio por cada habitación adicional:"</span>, coeficiente_dormitorios))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Incremento en el precio por cada habitación adicional: 30.6779242174629"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Intervalo de confianza del 95% para el coeficiente de habitaciones:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Intervalo de confianza del 95% para el coeficiente de habitaciones:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb143"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(intervalo_confianza_dormitorios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %   97.5 %
NumDormitorios 22.81741 38.53844</code></pre>
</div>
</div>
<hr>
<ol start="25" type="1">
<li>¿Cual es la probabilidad de encontrar, en el barrio de Sol, un apartamento en alquiler con 3 dormitorios? ¿Cual es el intervalo de confianza de esa probabilidad?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb145"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Asumiendo que ya tienes el DataFrame barrio_sol</span></span>
<span id="cb145-2"><a href="#cb145-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb145-3"><a href="#cb145-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular la probabilidad de un apartamento con 3 dormitorios</span></span>
<span id="cb145-4"><a href="#cb145-4" aria-hidden="true" tabindex="-1"></a>total_apartamentos <span class="ot">=</span> <span class="fu">nrow</span>(barrio_sol)</span>
<span id="cb145-5"><a href="#cb145-5" aria-hidden="true" tabindex="-1"></a>apartamentos_3_dormitorios <span class="ot">=</span> <span class="fu">sum</span>(barrio_sol<span class="sc">$</span>NumDormitorios <span class="sc">==</span> <span class="dv">3</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb145-6"><a href="#cb145-6" aria-hidden="true" tabindex="-1"></a>probabilidad_3_dormitorios <span class="ot">=</span> apartamentos_3_dormitorios <span class="sc">/</span> total_apartamentos</span>
<span id="cb145-7"><a href="#cb145-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb145-8"><a href="#cb145-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular el intervalo de confianza del 95%</span></span>
<span id="cb145-9"><a href="#cb145-9" aria-hidden="true" tabindex="-1"></a>prop_error_estandar <span class="ot">&lt;-</span> <span class="fu">sqrt</span>((probabilidad_3_dormitorios <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> probabilidad_3_dormitorios)) <span class="sc">/</span> total_apartamentos)</span>
<span id="cb145-10"><a href="#cb145-10" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)  <span class="co"># Valor Z para un intervalo de confianza del 95%</span></span>
<span id="cb145-11"><a href="#cb145-11" aria-hidden="true" tabindex="-1"></a>intervalo_confianza <span class="ot">&lt;-</span> <span class="fu">c</span>(probabilidad_3_dormitorios <span class="sc">-</span> z <span class="sc">*</span> prop_error_estandar, probabilidad_3_dormitorios <span class="sc">+</span> z <span class="sc">*</span> prop_error_estandar)</span>
<span id="cb145-12"><a href="#cb145-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb145-13"><a href="#cb145-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar los resultados</span></span>
<span id="cb145-14"><a href="#cb145-14" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Probabilidad de encontrar un apartamento con 3 dormitorios en Sol:"</span>, probabilidad_3_dormitorios))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Probabilidad de encontrar un apartamento con 3 dormitorios en Sol: 0.0666666666666667"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb147"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Intervalo de confianza del 95% para esta probabilidad:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Intervalo de confianza del 95% para esta probabilidad:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb149"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb149-1"><a href="#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(intervalo_confianza)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.00354983 0.12978350</code></pre>
</div>
</div>
<hr>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>